pipeline {
    agent none
    stages {
        stage('Build') {
            agent{
                dockerfile{
                    dir 'build_scripts/build_stage'
                }
            }
            steps {
                echo 'Building..'
                sh 'python3 -m build --wheel --outdir build/ c_module_source/sim/'	
                stash(name: 'compiled-results', includes: 'build/*.whl')	
            }
        }
        stage('Test') {
            agent{
                dockerfile{
                    dir 'build_scripts/testing_stage'
                }
            }
            
            steps {
                unstash 'compiled-results'
                sh 'ls'
                sh """
                    . /venv/bin/activate
                    pip install build/physicsEnv*.whl
                    pytest --junit-xml test-reports/results.xml build_scripts/testing_stage/tests.py
                    """
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('Deliver') {
            agent any
            steps {
                echo 'Deploying....'
                archiveArtifacts "build/physicsEnv*.whl"
                archiveArtifacts "test-reports/results.xml"
            }
        }
    }
}