version: "3.9"
services:
  peer1:
    build: ./peer1/
    ports:
      - "16543"
    environment:
      - PYTHONUNBUFFERED=1
 
  peer2:
    build: ./peer2/
    ports:
      - "16543"
    environment:
      - PYTHONUNBUFFERED=1